openapi: 3.0.0
info:
  title: Bank service API
  version: 0.0.1
servers:
  - url: http://localhost:9876/
    description: Localhost server


tags:
  - name: user
  - name: report
paths:
  /v1/user/{user_id}/reserve:
    post:
      tags:
        - user
      summary: Зарезервировать деньги
      parameters:
        - $ref: "#/components/parameters/user_id"
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/service_order_amount"
                - type: object
                  properties:
                    description:
                      type: string
                      description: Причина резервирования
                      example: "Оплата услуги связи"
                - type: object
                  properties:
                    service_name:
                      type: string
                      description: Название услуги с заданным Id (хранится последнее переданное)
                      example: Услуга связи

      responses:
        '204':
          description: Успешно зарезервировано
        '400':
          $ref: "#/components/responses/bad_request_error"
        '500':
          $ref: "#/components/responses/internal_server_error"


  /v1/user/{user_id}/balance:
    get:
      tags:
        - user
      summary: Получить баланс пользователя
      parameters:
        - $ref: "#/components/parameters/user_id"
      responses:
        '200':
          description: Успешно получен баланс пользователя
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/balance"
        '400':
          $ref: "#/components/schemas/bad_request_error"
        '500':
          $ref: "#/components/responses/internal_server_error"

    post:
      tags:
        - user
      summary: Пополнить баланс пользователя
      parameters:
        - $ref: "#/components/parameters/user_id"
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/amount"
                - name: description
                  type: object
                  properties:
                    description:
                      example: Пополнение VISA
                      type: string
      responses:
        '204':
          description: Успешно пополнен баланс пользователя
        '400':
          $ref: "#/components/responses/bad_request_error"
        '500':
          $ref: "#/components/responses/internal_server_error"


  /v1/report/{year}/{month}:
    get:
      tags:
        - report
      summary: Получить месячный отчет
      parameters:
        - name: year
          in: path
          required: True
          description: Год
          schema:
            type: integer
        - name: month
          in: path
          required: True
          description: Год
          schema:
            type: integer
      responses:
        '200':
          description: Успешно получена ссылка на отчет
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: Ссылка на отчет
                    example: http://localhost:80/somefile.csv
        '400':
          $ref: "#/components/responses/bad_request_error"
        '500':
          $ref: "#/components/responses/internal_server_error"


  /v1/user/{user_id}/history/{json}:
    get:
      tags:
        - user
      summary: Получить историю операций
      parameters:
        - $ref: "#/components/parameters/user_id"
        - name: json
          in: path
          schema:
            $ref: "#/components/schemas/history_params"
          required: true

      responses:
        '200':
          description: Успешно получена история операций
          content:
            application/json:
              schema:
                properties:
                  length:
                    type: integer
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/history_record"
        '400':
          $ref: "#/components/responses/bad_request_error"
        '500':
          $ref: "#/components/responses/internal_server_error"

  /v1/user/{user_id}/balance/recognize:
    post:
      tags:
        - user
      summary: Признать выручку
      parameters:
        - $ref: "#/components/parameters/user_id"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/service_order_amount"
      responses:
        '204':
          description: Успешно признана
        '400':
          $ref: "#/components/responses/bad_request_error"
        '500':
          $ref: "#/components/responses/internal_server_error"


components:
  schemas:
    history_params:
      type: object
      properties:
        limit:
          type: integer
        offset:
          type: integer
        sort_by:
          type: string
          enum:
            - timestamp
            - amount
          description: Поле сортировки
        reverse:
          type: boolean
          description: False - по возрастанию, True - по убыванию
    history_record:
      type: object
      properties:
        date:
          type: integer
          description: Время выполнения операции
        amount:
          type: integer
          description: Потраченная сумма
        description:
          type: string
          description: Комментарий
      required:
        - date
        - amount
        - description

    bad_request_error:
      type: object
      properties:
        msg:
          type: string
          description: Описание ошибки
          example: invalid user id
      required:
        - msg

    balance:
      type: object
      properties:
        balance:
          type: string
          description: Баланс пользователя
          example: 123.99
      required:
        - balance

    amount:
      type: object
      properties:
        amount:
          type: string
          description: Количество денег, больше 0
          example: 100.13
      required:
        - amount
    service_order_amount:
      type: object
      properties:
        service_id:
          type: integer
          description: Идентификатор услуги
          example: 123
        order_id:
          type: integer
          description: Идентификатор заказа
          example: 345
        amount:
          type: string
          description: Количество денег
          example: 100.13
      required:
        - service_id
        - order_id
        - amount

  responses:
    bad_request_error:
      description: Невалидные данные
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/bad_request_error"
    internal_server_error:
      description: Произошла внутренняя ошибка

  parameters:
    user_id:
      name: user_id
      in: path
      description: Идентификатор пользователя
      example: 111
      required: True
      schema:
        type: integer
      
    
              